// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchResponse.proto

package com.evol.protobuftest.domain;

public final class SearchResponse {
  private SearchResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string url = 1;</code>
     * @return The url.
     */
    String getUrl();
    /**
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>repeated string snippets = 3;</code>
     * @return A list containing the snippets.
     */
    java.util.List<String>
        getSnippetsList();
    /**
     * <code>repeated string snippets = 3;</code>
     * @return The count of snippets.
     */
    int getSnippetsCount();
    /**
     * <code>repeated string snippets = 3;</code>
     * @param index The index of the element to return.
     * @return The snippets at the given index.
     */
    String getSnippets(int index);
    /**
     * <code>repeated string snippets = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the snippets at the given index.
     */
    com.google.protobuf.ByteString
        getSnippetsBytes(int index);
  }
  /**
   * Protobuf type {@code Result}
   */
  public static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Result)
      ResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      url_ = "";
      title_ = "";
      snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Result();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                snippets_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              snippets_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          snippets_ = snippets_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.evol.protobuftest.domain.SearchResponse.internal_static_Result_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.evol.protobuftest.domain.SearchResponse.internal_static_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.evol.protobuftest.domain.SearchResponse.Result.class, com.evol.protobuftest.domain.SearchResponse.Result.Builder.class);
    }

    public static final int URL_FIELD_NUMBER = 1;
    private volatile Object url_;
    /**
     * <code>string url = 1;</code>
     * @return The url.
     */
    @Override
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    @Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile Object title_;
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @Override
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SNIPPETS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList snippets_;
    /**
     * <code>repeated string snippets = 3;</code>
     * @return A list containing the snippets.
     */
    public com.google.protobuf.ProtocolStringList
        getSnippetsList() {
      return snippets_;
    }
    /**
     * <code>repeated string snippets = 3;</code>
     * @return The count of snippets.
     */
    public int getSnippetsCount() {
      return snippets_.size();
    }
    /**
     * <code>repeated string snippets = 3;</code>
     * @param index The index of the element to return.
     * @return The snippets at the given index.
     */
    public String getSnippets(int index) {
      return snippets_.get(index);
    }
    /**
     * <code>repeated string snippets = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the snippets at the given index.
     */
    public com.google.protobuf.ByteString
        getSnippetsBytes(int index) {
      return snippets_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      for (int i = 0; i < snippets_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, snippets_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < snippets_.size(); i++) {
          dataSize += computeStringSizeNoTag(snippets_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSnippetsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.evol.protobuftest.domain.SearchResponse.Result)) {
        return super.equals(obj);
      }
      com.evol.protobuftest.domain.SearchResponse.Result other = (com.evol.protobuftest.domain.SearchResponse.Result) obj;

      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getSnippetsList()
          .equals(other.getSnippetsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      if (getSnippetsCount() > 0) {
        hash = (37 * hash) + SNIPPETS_FIELD_NUMBER;
        hash = (53 * hash) + getSnippetsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.evol.protobuftest.domain.SearchResponse.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.evol.protobuftest.domain.SearchResponse.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Result)
        com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.evol.protobuftest.domain.SearchResponse.internal_static_Result_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.evol.protobuftest.domain.SearchResponse.internal_static_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.evol.protobuftest.domain.SearchResponse.Result.class, com.evol.protobuftest.domain.SearchResponse.Result.Builder.class);
      }

      // Construct using com.evol.protobuftest.domain.SearchResponse.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        url_ = "";

        title_ = "";

        snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.evol.protobuftest.domain.SearchResponse.internal_static_Result_descriptor;
      }

      @Override
      public com.evol.protobuftest.domain.SearchResponse.Result getDefaultInstanceForType() {
        return com.evol.protobuftest.domain.SearchResponse.Result.getDefaultInstance();
      }

      @Override
      public com.evol.protobuftest.domain.SearchResponse.Result build() {
        com.evol.protobuftest.domain.SearchResponse.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.evol.protobuftest.domain.SearchResponse.Result buildPartial() {
        com.evol.protobuftest.domain.SearchResponse.Result result = new com.evol.protobuftest.domain.SearchResponse.Result(this);
        int from_bitField0_ = bitField0_;
        result.url_ = url_;
        result.title_ = title_;
        if (((bitField0_ & 0x00000001) != 0)) {
          snippets_ = snippets_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.snippets_ = snippets_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.evol.protobuftest.domain.SearchResponse.Result) {
          return mergeFrom((com.evol.protobuftest.domain.SearchResponse.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.evol.protobuftest.domain.SearchResponse.Result other) {
        if (other == com.evol.protobuftest.domain.SearchResponse.Result.getDefaultInstance()) return this;
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.snippets_.isEmpty()) {
          if (snippets_.isEmpty()) {
            snippets_ = other.snippets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSnippetsIsMutable();
            snippets_.addAll(other.snippets_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.evol.protobuftest.domain.SearchResponse.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.evol.protobuftest.domain.SearchResponse.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object url_ = "";
      /**
       * <code>string url = 1;</code>
       * @return The url.
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string url = 1;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 1;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 1;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSnippetsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          snippets_ = new com.google.protobuf.LazyStringArrayList(snippets_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @return A list containing the snippets.
       */
      public com.google.protobuf.ProtocolStringList
          getSnippetsList() {
        return snippets_.getUnmodifiableView();
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @return The count of snippets.
       */
      public int getSnippetsCount() {
        return snippets_.size();
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @param index The index of the element to return.
       * @return The snippets at the given index.
       */
      public String getSnippets(int index) {
        return snippets_.get(index);
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the snippets at the given index.
       */
      public com.google.protobuf.ByteString
          getSnippetsBytes(int index) {
        return snippets_.getByteString(index);
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @param index The index to set the value at.
       * @param value The snippets to set.
       * @return This builder for chaining.
       */
      public Builder setSnippets(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSnippetsIsMutable();
        snippets_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @param value The snippets to add.
       * @return This builder for chaining.
       */
      public Builder addSnippets(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSnippetsIsMutable();
        snippets_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @param values The snippets to add.
       * @return This builder for chaining.
       */
      public Builder addAllSnippets(
          Iterable<String> values) {
        ensureSnippetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, snippets_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSnippets() {
        snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @param value The bytes of the snippets to add.
       * @return This builder for chaining.
       */
      public Builder addSnippetsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSnippetsIsMutable();
        snippets_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Result)
    }

    // @@protoc_insertion_point(class_scope:Result)
    private static final com.evol.protobuftest.domain.SearchResponse.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.evol.protobuftest.domain.SearchResponse.Result();
    }

    public static com.evol.protobuftest.domain.SearchResponse.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      @Override
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    @Override
    public com.evol.protobuftest.domain.SearchResponse.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageSearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageSearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>int32 sub_code = 3;</code>
     * @return The subCode.
     */
    int getSubCode();

    /**
     * <code>string sub_msg = 4;</code>
     * @return The subMsg.
     */
    String getSubMsg();
    /**
     * <code>string sub_msg = 4;</code>
     * @return The bytes for subMsg.
     */
    com.google.protobuf.ByteString
        getSubMsgBytes();

    /**
     * <code>double temp = 5;</code>
     * @return The temp.
     */
    double getTemp();

    /**
     * <code>string username = 6;</code>
     * @return The username.
     */
    String getUsername();
    /**
     * <code>string username = 6;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string nick = 7;</code>
     * @return The nick.
     */
    String getNick();
    /**
     * <code>string nick = 7;</code>
     * @return The bytes for nick.
     */
    com.google.protobuf.ByteString
        getNickBytes();

    /**
     * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
     * @return The enum numeric value on the wire for corpus.
     */
    int getCorpusValue();
    /**
     * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
     * @return The corpus.
     */
    com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus getCorpus();

    /**
     * <code>repeated .Result results = 9;</code>
     */
    java.util.List<com.evol.protobuftest.domain.SearchResponse.Result>
        getResultsList();
    /**
     * <code>repeated .Result results = 9;</code>
     */
    com.evol.protobuftest.domain.SearchResponse.Result getResults(int index);
    /**
     * <code>repeated .Result results = 9;</code>
     */
    int getResultsCount();
    /**
     * <code>repeated .Result results = 9;</code>
     */
    java.util.List<? extends com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder>
        getResultsOrBuilderList();
    /**
     * <code>repeated .Result results = 9;</code>
     */
    com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder getResultsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code MessageSearchResponse}
   */
  public static final class MessageSearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageSearchResponse)
      MessageSearchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageSearchResponse.newBuilder() to construct.
    private MessageSearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageSearchResponse() {
      msg_ = "";
      subMsg_ = "";
      username_ = "";
      nick_ = "";
      corpus_ = 0;
      results_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageSearchResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageSearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 24: {

              subCode_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              subMsg_ = s;
              break;
            }
            case 41: {

              temp_ = input.readDouble();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              nick_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              corpus_ = rawValue;
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                results_ = new java.util.ArrayList<com.evol.protobuftest.domain.SearchResponse.Result>();
                mutable_bitField0_ |= 0x00000001;
              }
              results_.add(
                  input.readMessage(com.evol.protobuftest.domain.SearchResponse.Result.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.evol.protobuftest.domain.SearchResponse.internal_static_MessageSearchResponse_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.evol.protobuftest.domain.SearchResponse.internal_static_MessageSearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.class, com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code MessageSearchResponse.Corpus}
     */
    public enum Corpus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      UNIVERSAL(0),
      /**
       * <code>WEB = 1;</code>
       */
      WEB(1),
      /**
       * <code>IMAGES = 2;</code>
       */
      IMAGES(2),
      /**
       * <code>LOCAL = 3;</code>
       */
      LOCAL(3),
      /**
       * <code>NEWS = 4;</code>
       */
      NEWS(4),
      /**
       * <code>PRODUCTS = 5;</code>
       */
      PRODUCTS(5),
      /**
       * <code>VIDEO = 6;</code>
       */
      VIDEO(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOIVE = 6;</code>
       */
      public static final Corpus MOIVE = VIDEO;
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      public static final int UNIVERSAL_VALUE = 0;
      /**
       * <code>WEB = 1;</code>
       */
      public static final int WEB_VALUE = 1;
      /**
       * <code>IMAGES = 2;</code>
       */
      public static final int IMAGES_VALUE = 2;
      /**
       * <code>LOCAL = 3;</code>
       */
      public static final int LOCAL_VALUE = 3;
      /**
       * <code>NEWS = 4;</code>
       */
      public static final int NEWS_VALUE = 4;
      /**
       * <code>PRODUCTS = 5;</code>
       */
      public static final int PRODUCTS_VALUE = 5;
      /**
       * <code>VIDEO = 6;</code>
       */
      public static final int VIDEO_VALUE = 6;
      /**
       * <code>MOIVE = 6;</code>
       */
      public static final int MOIVE_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Corpus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Corpus forNumber(int value) {
        switch (value) {
          case 0: return UNIVERSAL;
          case 1: return WEB;
          case 2: return IMAGES;
          case 3: return LOCAL;
          case 4: return NEWS;
          case 5: return PRODUCTS;
          case 6: return VIDEO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Corpus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Corpus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Corpus>() {
              public Corpus findValueByNumber(int number) {
                return Corpus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Corpus[] VALUES = getStaticValuesArray();
      private static Corpus[] getStaticValuesArray() {
        return new Corpus[] {
          UNIVERSAL, WEB, IMAGES, LOCAL, NEWS, PRODUCTS, VIDEO, MOIVE, 
        };
      }
      public static Corpus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Corpus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageSearchResponse.Corpus)
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile Object msg_;
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @Override
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUB_CODE_FIELD_NUMBER = 3;
    private int subCode_;
    /**
     * <code>int32 sub_code = 3;</code>
     * @return The subCode.
     */
    @Override
    public int getSubCode() {
      return subCode_;
    }

    public static final int SUB_MSG_FIELD_NUMBER = 4;
    private volatile Object subMsg_;
    /**
     * <code>string sub_msg = 4;</code>
     * @return The subMsg.
     */
    @Override
    public String getSubMsg() {
      Object ref = subMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string sub_msg = 4;</code>
     * @return The bytes for subMsg.
     */
    @Override
    public com.google.protobuf.ByteString
        getSubMsgBytes() {
      Object ref = subMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMP_FIELD_NUMBER = 5;
    private double temp_;
    /**
     * <code>double temp = 5;</code>
     * @return The temp.
     */
    @Override
    public double getTemp() {
      return temp_;
    }

    public static final int USERNAME_FIELD_NUMBER = 6;
    private volatile Object username_;
    /**
     * <code>string username = 6;</code>
     * @return The username.
     */
    @Override
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 6;</code>
     * @return The bytes for username.
     */
    @Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICK_FIELD_NUMBER = 7;
    private volatile Object nick_;
    /**
     * <code>string nick = 7;</code>
     * @return The nick.
     */
    @Override
    public String getNick() {
      Object ref = nick_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nick_ = s;
        return s;
      }
    }
    /**
     * <code>string nick = 7;</code>
     * @return The bytes for nick.
     */
    @Override
    public com.google.protobuf.ByteString
        getNickBytes() {
      Object ref = nick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORPUS_FIELD_NUMBER = 8;
    private int corpus_;
    /**
     * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
     * @return The enum numeric value on the wire for corpus.
     */
    @Override public int getCorpusValue() {
      return corpus_;
    }
    /**
     * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
     * @return The corpus.
     */
    @Override public com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus getCorpus() {
      @SuppressWarnings("deprecation")
      com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus result = com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus.valueOf(corpus_);
      return result == null ? com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus.UNRECOGNIZED : result;
    }

    public static final int RESULTS_FIELD_NUMBER = 9;
    private java.util.List<com.evol.protobuftest.domain.SearchResponse.Result> results_;
    /**
     * <code>repeated .Result results = 9;</code>
     */
    @Override
    public java.util.List<com.evol.protobuftest.domain.SearchResponse.Result> getResultsList() {
      return results_;
    }
    /**
     * <code>repeated .Result results = 9;</code>
     */
    @Override
    public java.util.List<? extends com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder>
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <code>repeated .Result results = 9;</code>
     */
    @Override
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated .Result results = 9;</code>
     */
    @Override
    public com.evol.protobuftest.domain.SearchResponse.Result getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated .Result results = 9;</code>
     */
    @Override
    public com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (subCode_ != 0) {
        output.writeInt32(3, subCode_);
      }
      if (!getSubMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, subMsg_);
      }
      if (temp_ != 0D) {
        output.writeDouble(5, temp_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, username_);
      }
      if (!getNickBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nick_);
      }
      if (corpus_ != com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus.UNIVERSAL.getNumber()) {
        output.writeEnum(8, corpus_);
      }
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(9, results_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (subCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, subCode_);
      }
      if (!getSubMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, subMsg_);
      }
      if (temp_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, temp_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, username_);
      }
      if (!getNickBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nick_);
      }
      if (corpus_ != com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus.UNIVERSAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, corpus_);
      }
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, results_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse)) {
        return super.equals(obj);
      }
      com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse other = (com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (getSubCode()
          != other.getSubCode()) return false;
      if (!getSubMsg()
          .equals(other.getSubMsg())) return false;
      if (Double.doubleToLongBits(getTemp())
          != Double.doubleToLongBits(
              other.getTemp())) return false;
      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getNick()
          .equals(other.getNick())) return false;
      if (corpus_ != other.corpus_) return false;
      if (!getResultsList()
          .equals(other.getResultsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + SUB_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSubCode();
      hash = (37 * hash) + SUB_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getSubMsg().hashCode();
      hash = (37 * hash) + TEMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getTemp()));
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + NICK_FIELD_NUMBER;
      hash = (53 * hash) + getNick().hashCode();
      hash = (37 * hash) + CORPUS_FIELD_NUMBER;
      hash = (53 * hash) + corpus_;
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageSearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageSearchResponse)
        com.evol.protobuftest.domain.SearchResponse.MessageSearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.evol.protobuftest.domain.SearchResponse.internal_static_MessageSearchResponse_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.evol.protobuftest.domain.SearchResponse.internal_static_MessageSearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.class, com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Builder.class);
      }

      // Construct using com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        subCode_ = 0;

        subMsg_ = "";

        temp_ = 0D;

        username_ = "";

        nick_ = "";

        corpus_ = 0;

        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.evol.protobuftest.domain.SearchResponse.internal_static_MessageSearchResponse_descriptor;
      }

      @Override
      public com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse getDefaultInstanceForType() {
        return com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.getDefaultInstance();
      }

      @Override
      public com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse build() {
        com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse buildPartial() {
        com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse result = new com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse(this);
        int from_bitField0_ = bitField0_;
        result.code_ = code_;
        result.msg_ = msg_;
        result.subCode_ = subCode_;
        result.subMsg_ = subMsg_;
        result.temp_ = temp_;
        result.username_ = username_;
        result.nick_ = nick_;
        result.corpus_ = corpus_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse) {
          return mergeFrom((com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse other) {
        if (other == com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getSubCode() != 0) {
          setSubCode(other.getSubCode());
        }
        if (!other.getSubMsg().isEmpty()) {
          subMsg_ = other.subMsg_;
          onChanged();
        }
        if (other.getTemp() != 0D) {
          setTemp(other.getTemp());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getNick().isEmpty()) {
          nick_ = other.nick_;
          onChanged();
        }
        if (other.corpus_ != 0) {
          setCorpusValue(other.getCorpusValue());
        }
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int subCode_ ;
      /**
       * <code>int32 sub_code = 3;</code>
       * @return The subCode.
       */
      @Override
      public int getSubCode() {
        return subCode_;
      }
      /**
       * <code>int32 sub_code = 3;</code>
       * @param value The subCode to set.
       * @return This builder for chaining.
       */
      public Builder setSubCode(int value) {
        
        subCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sub_code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubCode() {
        
        subCode_ = 0;
        onChanged();
        return this;
      }

      private Object subMsg_ = "";
      /**
       * <code>string sub_msg = 4;</code>
       * @return The subMsg.
       */
      public String getSubMsg() {
        Object ref = subMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sub_msg = 4;</code>
       * @return The bytes for subMsg.
       */
      public com.google.protobuf.ByteString
          getSubMsgBytes() {
        Object ref = subMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sub_msg = 4;</code>
       * @param value The subMsg to set.
       * @return This builder for chaining.
       */
      public Builder setSubMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sub_msg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubMsg() {
        
        subMsg_ = getDefaultInstance().getSubMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string sub_msg = 4;</code>
       * @param value The bytes for subMsg to set.
       * @return This builder for chaining.
       */
      public Builder setSubMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subMsg_ = value;
        onChanged();
        return this;
      }

      private double temp_ ;
      /**
       * <code>double temp = 5;</code>
       * @return The temp.
       */
      @Override
      public double getTemp() {
        return temp_;
      }
      /**
       * <code>double temp = 5;</code>
       * @param value The temp to set.
       * @return This builder for chaining.
       */
      public Builder setTemp(double value) {
        
        temp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double temp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemp() {
        
        temp_ = 0D;
        onChanged();
        return this;
      }

      private Object username_ = "";
      /**
       * <code>string username = 6;</code>
       * @return The username.
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string username = 6;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 6;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 6;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private Object nick_ = "";
      /**
       * <code>string nick = 7;</code>
       * @return The nick.
       */
      public String getNick() {
        Object ref = nick_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nick = 7;</code>
       * @return The bytes for nick.
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        Object ref = nick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nick = 7;</code>
       * @param value The nick to set.
       * @return This builder for chaining.
       */
      public Builder setNick(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nick = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearNick() {
        
        nick_ = getDefaultInstance().getNick();
        onChanged();
        return this;
      }
      /**
       * <code>string nick = 7;</code>
       * @param value The bytes for nick to set.
       * @return This builder for chaining.
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nick_ = value;
        onChanged();
        return this;
      }

      private int corpus_ = 0;
      /**
       * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
       * @return The enum numeric value on the wire for corpus.
       */
      @Override public int getCorpusValue() {
        return corpus_;
      }
      /**
       * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
       * @param value The enum numeric value on the wire for corpus to set.
       * @return This builder for chaining.
       */
      public Builder setCorpusValue(int value) {
        
        corpus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
       * @return The corpus.
       */
      @Override
      public com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus getCorpus() {
        @SuppressWarnings("deprecation")
        com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus result = com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus.valueOf(corpus_);
        return result == null ? com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
       * @param value The corpus to set.
       * @return This builder for chaining.
       */
      public Builder setCorpus(com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        corpus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageSearchResponse.Corpus corpus = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorpus() {
        
        corpus_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.evol.protobuftest.domain.SearchResponse.Result> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          results_ = new java.util.ArrayList<com.evol.protobuftest.domain.SearchResponse.Result>(results_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.evol.protobuftest.domain.SearchResponse.Result, com.evol.protobuftest.domain.SearchResponse.Result.Builder, com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder> resultsBuilder_;

      /**
       * <code>repeated .Result results = 9;</code>
       */
      public java.util.List<com.evol.protobuftest.domain.SearchResponse.Result> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public com.evol.protobuftest.domain.SearchResponse.Result getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder setResults(
          int index, com.evol.protobuftest.domain.SearchResponse.Result value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder setResults(
          int index, com.evol.protobuftest.domain.SearchResponse.Result.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder addResults(com.evol.protobuftest.domain.SearchResponse.Result value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder addResults(
          int index, com.evol.protobuftest.domain.SearchResponse.Result value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder addResults(
          com.evol.protobuftest.domain.SearchResponse.Result.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder addResults(
          int index, com.evol.protobuftest.domain.SearchResponse.Result.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder addAllResults(
          Iterable<? extends com.evol.protobuftest.domain.SearchResponse.Result> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public com.evol.protobuftest.domain.SearchResponse.Result.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public java.util.List<? extends com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder>
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public com.evol.protobuftest.domain.SearchResponse.Result.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            com.evol.protobuftest.domain.SearchResponse.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public com.evol.protobuftest.domain.SearchResponse.Result.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, com.evol.protobuftest.domain.SearchResponse.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .Result results = 9;</code>
       */
      public java.util.List<com.evol.protobuftest.domain.SearchResponse.Result.Builder>
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.evol.protobuftest.domain.SearchResponse.Result, com.evol.protobuftest.domain.SearchResponse.Result.Builder, com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder>
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.evol.protobuftest.domain.SearchResponse.Result, com.evol.protobuftest.domain.SearchResponse.Result.Builder, com.evol.protobuftest.domain.SearchResponse.ResultOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageSearchResponse)
    }

    // @@protoc_insertion_point(class_scope:MessageSearchResponse)
    private static final com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse();
    }

    public static com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageSearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<MessageSearchResponse>() {
      @Override
      public MessageSearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageSearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageSearchResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageSearchResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public com.evol.protobuftest.domain.SearchResponse.MessageSearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageSearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageSearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024SearchResponse.proto\"6\n\006Result\022\013\n\003url\030" +
      "\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\020\n\010snippets\030\003 \003(\t\"\267" +
      "\002\n\025MessageSearchResponse\022\014\n\004code\030\001 \001(\005\022\013" +
      "\n\003msg\030\002 \001(\t\022\020\n\010sub_code\030\003 \001(\005\022\017\n\007sub_msg" +
      "\030\004 \001(\t\022\014\n\004temp\030\005 \001(\001\022\020\n\010username\030\006 \001(\t\022\014" +
      "\n\004nick\030\007 \001(\t\022-\n\006corpus\030\010 \001(\0162\035.MessageSe" +
      "archResponse.Corpus\022\030\n\007results\030\t \003(\0132\007.R" +
      "esult\"i\n\006Corpus\022\r\n\tUNIVERSAL\020\000\022\007\n\003WEB\020\001\022" +
      "\n\n\006IMAGES\020\002\022\t\n\005LOCAL\020\003\022\010\n\004NEWS\020\004\022\014\n\010PROD" +
      "UCTS\020\005\022\t\n\005VIDEO\020\006\022\t\n\005MOIVE\020\006\032\002\020\001B1\n\037com." +
      "example.protobuftest.domainB\016SearchRespo" +
      "nseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Result_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result_descriptor,
        new String[] { "Url", "Title", "Snippets", });
    internal_static_MessageSearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MessageSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageSearchResponse_descriptor,
        new String[] { "Code", "Msg", "SubCode", "SubMsg", "Temp", "Username", "Nick", "Corpus", "Results", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
